server:
  port: 80

spring:
  application:
    name: springcloud-consumer-dept

#开启熔断服务
feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

