server: 
  port: 3344 

spring:
  application:
    name:  springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shiniaxiaomi/springcloud-config.git #GitHub上面的git仓库地址(不要使用SSH地址)
